language: python
install:
  - python setup.py develop
  - pip install tox
script: tox -e $TOXENV
notifications:
  email: false
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=nightly
  - TOXENV=pypy
